name: Fix Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Generate wrapper
        run: gradle wrapper

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Restore Gradle wrapper"
          title: "Restore Gradle wrapper"
          branch: fix/gradle-wrapper
          base: main
